source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sc-core-ext'

gem "rspec-rails"
gem "webrat"
gem "database_cleaner"
gem "cucumber-rails", '1.0.2'
gem "cucumber"
gem "launchy"

# gem 'genspec', "= 0.2.0.prerails3.2"
gem 'email_spec'

gem 'sqlite3-ruby', :require => 'sqlite3'
